### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Orpheusssl** [GabBiswajit/Profile-ui#1]
[Server thread/INFO]: Orpheussl joined the game
[21:39:01.495] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: Orpheussl
[21:39:01.496] [Server thread/CRITICAL]: Error: "Class "Biswajit\SimpleForm" not found" (EXCEPTION) in "plugins/Profile-ui-main/src/Biswajit/Profile" at line 30
--- Stack trace ---
  #0 plugins/Profile-ui-main/src/Biswajit/Profile(19): Biswajit\Profile->openMyForm(object pocketmine\player\Player#171584)
  #1 pmsrc/src/command/PluginCommand(46): Biswajit\Profile->onCommand(object pocketmine\player\Player#171584, object pocketmine\command\PluginCommand#41753, string[7] profile, array[0])
  #2 pmsrc/src/command/SimpleCommandMap(212): pocketmine\command\PluginCommand->execute(object pocketmine\player\Player#171584, string[7] profile, array[0])
  #3 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#171584, string[7] profile)
  #4 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#171584, string[7] profile)
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(823): pocketmine\player\Player->chat(string[8] /profile)
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#147599)
  #7 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#94073)
  #8 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#147599, string[30] M./profile..M...^}.2.........F)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[34] ..../(.O..Ie..e...W...y....V.g`p..)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[43] .9x=+..".Z..W^v.F. ... ..b ....lV.v....D...)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#187873)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1691433541.519)
  #16 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#7, string[34] C:\Users\..a..atay\Desktop\tekrar\, string[42] C:\Users\..a..atay\Desktop\tekrar\plugins\)
  #18 pmsrc/src/PocketMine(357): pocketmine\server()
  #19 pmsrc(11): require(string[78] phar://C:/Users/..a..atay/Desktop/tekrar/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[21:39:01.497] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[21:39:01.509] [Server thread/EMERGENCY]: Please upload the "C:/Users/Çağatay/Desktop/tekrar/crashdumps/Mon_Aug_7-21.39.01-+03_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[21:39:01.510] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by GabBiswajit** [comment]
Fix #Fix A Mistake

**Comment by GabBiswajit** [comment]
@Orpheusssl fix https://github.com/GabBiswajit/Profile-ui
